#!/usr/bin/env php
<?php

// Include the autoloader
if (file_exists(__DIR__ . '/../../autoload.php')) {
  require __DIR__ . '/../../autoload.php';
}
elseif (file_exists(__DIR__ . '/vendor/autoload.php')) {
  require __DIR__ . '/vendor/autoload.php';
}
else {
  require __DIR__ . '/src/bootstrap.php';
}

// Define constants
define('BASE_DIR', __DIR__);

// Initialize the generator.
$app = new StatonLab\FieldGenerator\Generator();
$prompt = $app->prompt();

// Run the generator
try {
  $path = $app->run();
} catch (Exception $exception) {
  $prompt->error($exception->getMessage());
  exit(1);
}

// Success!
$prompt->success('Field generated successfully.');
$prompt->success("The field can be found at {$path['field']}");
