#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} elseif (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/src/bootstrap.php';
}

$app = new StatonLab\FieldGenerator\Generator();
$prompt = $app->prompt();

try {
    $path = $app->run();
} catch (Exception $exception) {
    $prompt->error($exception->getMessage());
    exit(1);
}

$prompt->success('Field generated successfully.');
$prompt->success("The field can be found at {$path['field']}");
